const main = async () => {
  console.log('Hello World')
}

main().catch(console.error)
